apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-marafis
  namespace: website
spec:
  acme:
    secretName: wildcard-marafis-tls
    issuerRef:
      name: letsencrypt-wildcard
      kind: ClusterIssuer

    dnsNames:
      - marafis.com
      - "*.marafis.com"