apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-wildcard
spec:
  acme:
    email: oncmmr@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-wildcard-key

    solvers:
      - dns01:
          cloudDNS:
            project: marafis-com
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json