apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundcube
  namespace: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roundcube
  template:
    metadata:
      labels:
        app: roundcube
    spec:
      hostAliases:
        - ip: "94.130.107.251" # Force it to resolve externally to the host interface cleanly
          hostnames:
            - "mail.marafis.com"
      containers:
        - name: roundcube
          image: roundcube/roundcubemail:latest
          ports:
            - containerPort: 80
          env:
            # Point directly to the host's internal network gateway
            - name: ROUNDCUBEMAIL_DEFAULT_HOST
              value: "172.17.0.1"
            - name: ROUNDCUBEMAIL_DEFAULT_PORT
              value: "143"
            - name: ROUNDCUBEMAIL_SMTP_SERVER
              value: "172.17.0.1"
            - name: ROUNDCUBEMAIL_SMTP_PORT
              value: "587"