apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-pool
  namespace: metallb-system
spec:
  addresses:
    - 94.130.107.251-94.130.107.251
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public-l2
  namespace: metallb-system