version: '3.8'

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver

    hostname: mail
    domainname: marafis.com

    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"

    volumes:
      - /opt/mailserver/mail-data:/var/mail
      - /opt/mailserver/mail-state:/var/mail-state
      - /opt/mailserver/mail-logs:/var/log/mail
      - /opt/mailserver/certs:/tmp/dms/certs:ro

    environment:
      - OVERVIEW_ENABLED=0
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/dms/certs/fullchain.pem
      - SSL_KEY_PATH=/tmp/dms/certs/privkey.pem
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
      - ONE_DIR=1
      - LOG_LEVEL=info
      - PERMIT_DOCKER=network
      - UPDATE_CHECK_INTERVAL=1d
      - DOVECOT_AUTH_MECHANISMS=plain login
      - OUR_NETWORKS=10.42.0.0/16,10.43.0.0/16,10.0.0.0/24

    restart: always