# infra/email-ui-roundcube/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: roundcube-config
  namespace: website
data:
  config.user.inc.php: |
    <?php
    $config['default_host'] = 'tls://94.130.107.251';
    $config['smtp_server'] = 'tls://94.130.107.251';
    
    // FDisable strict upstream verification for local network peering
    $config['imap_conn_options'] = [
        'ssl' => [
            'verify_peer'       => false,
            'verify_peer_name'  => false,
            'allow_self_signed' => true,
            'peer_name'         => 'mail.marafis.com',
        ],
    ];
    $config['smtp_conn_options'] = [
        'ssl' => [
            'verify_peer'       => false,
            'verify_peer_name'  => false,
            'allow_self_signed' => true,
            'peer_name'         => 'mail.marafis.com',
        ],
    ];