apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundcube
  namespace: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roundcube
  template:
    metadata:
      labels:
        app: roundcube
    spec:
      hostAliases:
        - ip: "94.130.107.251" # Force it to resolve externally to the host interface cleanly
          hostnames:
            - "mail.marafis.com"
      containers:
        - name: roundcube
          image: roundcube/roundcubemail:latest
          ports:
            - containerPort: 80
          env:
            - name: ROUNDCUBEMAIL_DEFAULT_HOST
              value: "tls://mail.marafis.com"
            - name: ROUNDCUBEMAIL_DEFAULT_PORT
              value: "143"