apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundcube
  namespace: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roundcube
  template:
    metadata:
      labels:
        app: roundcube
    spec:
      containers:
        - name: roundcube
          image: roundcube/roundcubemail:latest
          ports:
            - containerPort: 80
          env:
            - name: ROUNDCUBEMAIL_DEFAULT_HOST
              value: "ssl://mail.marafis.com"
            - name: ROUNDCUBEMAIL_DEFAULT_PORT
              value: "993"