# infra/email-ui-roundcube/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundcube
  namespace: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roundcube
  template:
    metadata:
      labels:
        app: roundcube
    spec:
      hostAliases:
        - ip: "94.130.107.251"
          hostnames:
            - "mail.marafis.com"
      containers:
        - name: roundcube
          image: roundcube/roundcubemail:latest
          ports:
            - containerPort: 80
          env:
            - name: ROUNDCUBEMAIL_DEFAULT_HOST
              value: "ssl://mail.marafis.com"
            - name: ROUNDCUBEMAIL_DEFAULT_PORT
              value: "993"
            - name: ROUNDCUBEMAIL_SMTP_SERVER
              value: "tls://mail.marafis.com"
            - name: ROUNDCUBEMAIL_SMTP_PORT
              value: "587"
          volumeMounts:
            # Mount our custom config file directly into the config directory
            - name: config-volume
              mountPath: /var/www/html/config/config.user.inc.php
              subPath: config.user.inc.php
      volumes:
        - name: config-volume
          configMap:
            name: roundcube-config