apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  project: default

  source:
    repoURL: https://github.com/marafis/marafis-infra.git
    targetRevision: main
    path: infra/postgres

  destination:
    server: https://kubernetes.default.svc
    namespace: website

  syncPolicy:
    automated:
      prune: true
      selfHeal: true