apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: roundcube-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"

spec:
  project: default
  source:
    repoURL: 'https://github.com/marafis/marafis-infra.git'
    targetRevision: main
    path: infra/email-ui-roundcube

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: website

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true