apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strapi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  project: default

  source:
    repoURL: https://github.com/marafis/marafis-infra.git
    path: infra/strapi
    targetRevision: main

  destination:
    server: https://kubernetes.default.svc
    namespace: website

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false # Protects backend from accidental deletions
    syncOptions:
      - CreateNamespace=true # Ensures namespace exists regardless of which app syncs first